### ISSUE TITLE
TODO's (esp for those interested in helping on a package)

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/rgeocodio#2]
If you're interested in learning about how to work on packages, collaborate on package development, add the finishing touches to a package or write tests/code coverage checks just reply to this issue with a note of volunteering or submit a PR if you're already familiar with those things but just want some practice. Full co-author credit in the pkg `DESCRIPTION` for those who help.

TODOs

- [ ] a tad more error checking (especially processing API status codes
- [ ] more/better tests along with full code coverage
- [ ] Add R examples to the official documentation
